version: '3'
services:

  backend:
    build:
      context: ./backend
    ports:
      - 8081:8081

  frontend:
    build:
      context: ./frontend
    ports:
      - 83:80
    depends_on:
      - backend
