version: '3'
services:

  backend:
    build:
      context: ./backend
    ports:
      - 8081:8081
    networks:
      - nginx_proxy

  frontend:
    build:
      context: ./frontend
    ports:
      - 93:80
    depends_on:
      - backend
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
